#!/bin/bash

if [ -n "$BASH_VERSION" ]; then
    if [ -f "$HOME/.bashrc" ]; then
	. "$HOME/.bashrc"
    fi
fi

PATH="$HOME/.cargo/bin:$PATH"

export P4CONFIG=.p4config
export P4IGNORE=.p4ignore
export PACKAGE_MAKE_USE_BEAR=1
export INSTALL4J_JAVA_HOME_OVERRIDE=/usr/lib/jvm/java-8-openjdk-amd64/
export OS_CLOUD=openstack

export VISUAL="nvim"
export EDITOR="nvim"

if [ -e "$HOME/.nix-profile/etc/profile.d/nix.sh" ]
then
    . "$HOME/.nix-profile/etc/profile.d/nix.sh"
fi

if [ -e "$HOME/.cabal/bin" ]
then
    PATH="$HOME/.cabal/bin:$PATH"
fi
if [ -e "$HOME/.ghcup/bin" ]
then
    PATH="$HOME/.ghcup/bin:$PATH"
fi

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

export FZF_DEFAULT_COMMAND="fdfind --type f -I --ignore-file $HOME/.fdignore"

GNATSTUDIO_HOME="$HOME/.local/share/gnatstudio-23.0w-20220512-x86_64-linux-bin"
if [ -e "$GNATSTUDIO_HOME" ]
then
    PATH=$PATH:$GNATSTUDIO_HOME/bin
fi

if [ -e "/opt/Xilinx/Vivado/2022.2/bin" ]
then
    PATH="$PATH:/opt/Xilinx/Vivado/2022.2/bin"
fi
