- name: Add erlang key
  become: yes
  apt_key:
    url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
- name: Add erlang repo
  become: yes
  apt_repository:
    repo: "deb https://packages.erlang-solutions.com/ubuntu {{ ansible_distribution_release|lower }} contrib"
    filename: erlang-solutions
- name: Install apt packages 
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - elixir
