#!/bin/bash

set -e
set -x

sudo apt-get install python3-pip
python3 -m pip install --user dotdrop ansible
~/.local/bin/dotdrop install --profile unified-host

. ~/.profile
ansible-playbook -i hosts.ini playbook.yml --ask-sudo-pass
