#!/bin/bash

set -e
set -x

sudo add-apt-repository ppa:ansible/ansible
sudo apt-get install python3-pip ansible
python3 -m pip install --user dotdrop
~/.local/bin/dotdrop install --profile unified-host

. ~/.profile
ansible-playbook -i hosts.ini playbook.yml --ask-sudo-pass
