#!/bin/bash

set -e
set -x

if [ -z "$NO_BECOME_PROMPT" ]
then
    PROMPT=-K
fi

if ! command -v ansible-playbook
then
    sudo add-apt-repository -y ppa:ansible/ansible
    sudo apt-get install -y python3-pip ansible cowsay
fi

. dotfiles/profile

# This is a hack since ansible seems to randomly lock up my machine
sync

ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook -i hosts.ini -l "$(hostname)" playbook.yml $PROMPT
