- name: Add SBT key
  become: yes
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823
- name: Add SBT repo
  become: yes
  apt_repository:
    repo: "deb https://dl.bintray.com/sbt/debian /"
    state: present
- name: Add gradle PPA
  become: yes
  apt_repository:
    repo: "ppa:cwchien/gradle"
- name: Install apt packages
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - default-jdk
    - gradle
    - sbt
- name: Install coursier
  get_url:
    dest: "{{ lookup('env', 'HOME') }}/.local/bin/coursier"
    mode: u+rwx
    url: https://git.io/coursier
- name: Install metals-vim
  command: >
    coursier bootstrap
    --java-opt -Xss4m
    --java-opt -Xms100m
    --java-opt -Dmetals.client=LanguageClient-neovim
    org.scalameta:metals_2.12:0.7.0
    -r bintray:scalacenter/releases
    -r sonatype:snapshots
    -o "{{ lookup('env', 'HOME') }}/.local/bin/metals-vim"
    -f
  args:
    creates: "{{ lookup('env', 'HOME') }}/.local/bin/metals-vim"
