- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - fcitx
      - fcitx-googlepinyin
      - fcitx-pinyin
      - fcitx-sunpinyin
      - fcitx-table-wbpy
