- name: Install apt packages
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - fcitx
    - fcitx-googlepinyin
    - fcitx-pinyin
    - fcitx-sunpinyin
    - fcitx-table-wbpy
