- name: Prepare yarn repo key
  become: yes
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
- name: Add yarn repository
  become: yes
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    filename: yarn
- name: Install apt packages
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - nodejs
    - yarn
