- name: Prepare nodejs repo key
  become: true
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
- name: Add nodejs repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://deb.nodesource.com/node_14.x {{ ansible_distribution_release | lower }} main"
    filename: nodejs
- name: Prepare yarn repo key
  become: true
  ansible.builtin.apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
- name: Add yarn repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    filename: yarn
- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - nodejs
      - yarn
