- name: Prepare bazel repo key
  become: true
  ansible.builtin.apt_key:
    url: https://bazel.build/bazel-release.pub.gpg
- name: Add bazel repo
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8"
    filename: bazel
- name: Install apt package
  become: true
  ansible.builtin.apt:
    name: bazel
