---
- name: Set sshd config
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: "Port 28"
- name: Clear sshd config
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: "KbdInteractiveAuthentication no"
- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name: zfsutils-linux
