[tool.poetry]
name = "j2math"
version = "0.1.0"
description = ""
authors = ["Jennifer Wilcox <jennifer@nitori.org>"]

[tool.poetry.dependencies]
python = "~3.10"
bpython = "^0.23"
Pint = "^0.19.2"
numpy = "^1.23.3"
scipy = "^1.9.1"
