- name: Setup racket PPA
  become: yes
  apt_repository:
    repo: ppa:plt/racket
- name: Install apt packages
  become: yes
  apt:
    name: "{{ item }}"
  loop:
    - sbcl
    - sbcl-source
    - sbcl-doc
    - cl-quicklisp
    - racket
- name: Clone racket
  git:
    repo: https://github.com/racket/racket.git
    dest: "{{ lookup('env','HOME') }}/.local/src/racket"
    version: v8.6
    update: false
- name: Build zuo
  shell: |
    cd ~/.local/src/racket/racket/src/zuo
    ./configure --prefix=$HOME/.local
    make
    make install
  args:
    creates: "{{ lookup('env','HOME') }}/.local/bin/zuo"
