- name: Setup racket PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:plt/racket
- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - sbcl
    - sbcl-source
    - sbcl-doc
    - cl-quicklisp
    - racket
- name: Clone racket
  ansible.builtin.git:
    repo: https://github.com/racket/racket.git
    dest: "{{ home }}/.local/src/racket"
    version: v8.6
    update: false
- name: Build zuo
  ansible.builtin.shell: |
    cd ~/.local/src/racket/racket/src/zuo
    ./configure --prefix=$HOME/.local
    make
    make install
  args:
    creates: "{{ home }}/.local/bin/zuo"
