- name: Create destinations
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ home }}/.local/share/vhdl-ls"
- name: Download VHDL LS
  ansible.builtin.get_url:
    url: https://github.com/VHDL-LS/rust_hdl/releases/download/v0.85.0/vhdl_ls-x86_64-unknown-linux-musl.zip
    dest: "{{ home }}/.local/share/vhdl_ls-0.85.0.zip"
    checksum: sha256:2a828058251addcdcc1c115da1b1d5c12de5f6b514718b8977904a8a28f71f61
    mode: "0644"
  register: vhdl_ls_download
- name: Install VHDL LS
  ansible.builtin.unarchive:
    src: "{{ vhdl_ls_download.dest }}"
    dest: "{{ home }}/.local/share/vhdl-ls/"
  when: vhdl_ls_download.changed
- name: Link VHDL LS
  ansible.builtin.file:
    src: "{{ home }}/.local/share/vhdl-ls/vhdl_ls-x86_64-unknown-linux-musl/bin/vhdl_ls"
    dest: "{{ home }}/.local/bin/vhdl_ls"
    state: link
    force: true
