- name: Setup ULX3S udev rule
  become: yes
  copy:
    dest: /etc/udev/rules.d/80-fpga-ulx3s.rules
    content: |
      # this is for usb-serial tty device
      SUBSYSTEM=="tty", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6015", MODE="664", GROUP="dialout"
      # this is for ujprog libusb access
      ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6015", GROUP="dialout", MODE="666"
