- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - gtkwave
      - plantuml
- name: Create destinations
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ home }}/.local/share/oss-cad-suite"
    - "{{ home }}/.local/share/vhdl-ls"
- name: Download oss-cad-suite
  ansible.builtin.get_url:
    url: https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2025-09-21/oss-cad-suite-linux-x64-20250921.tgz
    dest: "{{ home }}/.local/share/oss-cad-suite-linux-x64-20250316.tgz"
    checksum: sha256:3c9a7f639e89ae5e8972254cb3bbd42133fac11ad95dedaf7efb5ec18bde22f9
    mode: "0644"
  register: cad_download
- name: Delete old oss-cad-suite
  ansible.builtin.file:
    dest: "{{ home }}/.local/share/oss-cad-suite"
    state: absent
  when: cad_download.changed
- name: Install oss-cad-suite
  ansible.builtin.unarchive:
    src: "{{ cad_download.dest }}"
    dest: "{{ home }}/.local/share"
  when: cad_download.changed
- name: Download VHDL LS
  ansible.builtin.get_url:
    url: https://github.com/VHDL-LS/rust_hdl/releases/download/v0.84.0/vhdl_ls-x86_64-unknown-linux-gnu.zip
    dest: "{{ home }}/.local/share/vhdl_ls-0.84.0.zip"
    checksum: sha256:e2f1550c987c5f4226cc0f854f6963dbdc3badddaa8a82f4a550e183c0c6b503
    mode: "0644"
  register: vhdl_ls_download
- name: Install VHDL LS
  ansible.builtin.unarchive:
    src: "{{ vhdl_ls_download.dest }}"
    dest: "{{ home }}/.local/share/vhdl-ls/"
  when: vhdl_ls_download.changed
- name: Link VHDL LS
  ansible.builtin.file:
    src: "{{ home }}/.local/share/vhdl-ls/vhdl_ls-x86_64-unknown-linux-gnu/bin/vhdl_ls"
    dest: "{{ home }}/.local/bin/vhdl_ls"
    state: link
    force: true
- name: Download nvc
  ansible.builtin.get_url:
    url: https://github.com/nickg/nvc/releases/download/r1.15.1/nvc_1.15.1.git20250122.db31b1a-1_amd64_ubuntu-24.04.deb
    dest: "{{ home }}/.local/share/nvc_1.15.1.deb"
    checksum: sha256:2fae62e9d7dc33bc3b054aa397e205f1669e0ae3d7457e02f16a2129a5fb8f4a
    mode: "0644"
  register: nvc_download
- name: Install nvc package
  become: true
  ansible.builtin.apt:
    deb: "{{ nvc_download.dest }}"
  when: nvc_download.changed
- name: Create destinations
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "/etc/udev/rules.d/"
- name: Install USB blaster udev rules
  become: true
  ansible.builtin.copy:
    src: dotfiles/udev/51-usbblaster.rules
    dest: /etc/udev/rules.d/51-usbblaster.rules
    mode: "0644"
