- name: Download oss-cad-suite
  ansible.builtin.get_url:
    url: https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2024-12-18/oss-cad-suite-linux-x64-20241218.tgz
    dest: "{{ home }}/.local/share/oss-cad-suite-linux-x64-20241218.tgz"
    checksum: sha256:733ca13b5156e019baca8c9d84bdd1bae6e79eeefc58c0048cc15332fe2de61d
    mode: "0644"
  register: cad_download
- name: Create destination
  ansible.builtin.file:
    dest: "{{ home }}/.local/share/oss-cad-suite"
    state: directory
    mode: "0755"
- name: Install oss-cad-suite
  ansible.builtin.unarchive:
    src: "{{ cad_download.dest }}"
    dest: "{{ home }}/.local/share"
  when: cad_download.changed
