- name: Get go
  get_url:
    dest: "{{ lookup('env', 'HOME') }}/.local/share/go-1.13.tar.gz"
    url: https://dl.google.com/go/go1.13.linux-amd64.tar.gz
- name: Unpack go
  unarchive:
    src: "{{ lookup('env', 'HOME') }}/.local/share/go-1.13.tar.gz"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/"
