---
- name: Install apt packages
  become: true
  apt:
    name: "{{ item }}"
  loop:
    - emacs
    - fonts-nanum
    - fonts-nanum-extra
    # This is for vterm
    - libtool
    - libtool-bin
- name: Install spacemacs
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: "{{ lookup('env','HOME') }}/.emacs.d"
    version: develop
    update: false
