- name: Install stack
  become: yes
  shell: curl -sSL https://get.haskellstack.org/ | sh
  args:
    creates: /usr/local/bin/stack
- name: Install apt packages
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - libtinfo-dev
