#!/bin/bash

set -eux -o pipefail

echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

apt-get update
apt-get dist-upgrade -y
apt-get install -y sudo passwd software-properties-common build-essential

useradd --user-group --create-home -G sudo jwilcox
echo "jwilcox ALL=(ALL) NOPASSWD:ALL" >>/etc/sudoers
