---
- name: Setup configuration directories
  ansible.builtin.file:
    dest: "{{ home }}/{{ item }}"
    state: directory
    mode: "755"
  with_items:
    - .config
    - .local/bin
    - .local/src
    - .virtualenvs
    - .local/share
    - .fonts
    - .vsnip-local
- name: Setup sensitive directories
  ansible.builtin.file:
    dest: "{{ home }}/{{ item }}"
    state: directory
    mode: "700"
  with_items:
    - .gnupg
    - .ssh
- name: Install dotfiles
  ansible.builtin.file:
    src: "{{ playbook_dir }}/dotfiles/{{ item.src }}"
    dest: "{{ home }}/{{ item.dest }}"
    state: link
    force: true
  with_items:
    - src: gitignore
      dest: .gitignore
    - src: fdignore
      dest: .fdignore
    - src: bashrc
      dest: .bashrc
    - src: profile
      dest: .profile
    - src: tmux.conf
      dest: .tmux.conf
    - src: vsnip
      dest: .vsnip
- name: Create sshd config directory
  become: true
  ansible.builtin.file:
    dest: "/etc/ssh/sshd_config.d"
    state: directory
    mode: "755"
- name: Install etc config
  become: true
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/dotfiles/etc/{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
  with_items:
    - src: sshd_extras.conf
      dest: /etc/ssh/sshd_config.d/sshd_extras.conf
- name: Install local scripts
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ home }}/.local/bin/{{ item | basename }}"
    state: link
    force: true
  with_fileglob:
    - "{{ playbook_dir }}/bin/*"
- name: Generate ssh-config
  ansible.builtin.template:
    src: templates/ssh-config
    dest: "{{ home }}/.ssh/config"
    mode: "600"
- name: Generate templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "655"
  loop:
    - src: templates/gitconfig
      dest: "{{ home }}/.gitconfig"
- name: Update apt packages
  become: true
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true
- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - black
      - build-essential
      - cowsay
      - curl
      - fd-find
      - fzf
      - gdb-multiarch
      - git
      - gnupg2
      - htop
      - btop
      - keychain
      - ncdu
      - neovim
      - ninja-build
      - podman
      - pkg-config
      - python3-debian
      - python3-venv
      - ripgrep
      - shellcheck
      - sl
      - tmux
      - tree
      - unzip
      - xclip
