---
- name: Make required directories
  become: true
  file:
    dest: /opt/build/libqalculate
    state: directory

- name: Remove old symlinks
  ansible.builtin.file:
    dest: "{{ home }}/.local/bin/{{ item }}"
    state: absent
  loop:
    - qalc
    - qalculate

- name: Get libqalculate
  become: true
  get_url:
    url: "https://github.com/Qalculate/libqalculate/releases/download/v{{ qalc_version }}/libqalculate-{{ qalc_version }}.tar.gz"
    dest: "/opt/build/libqalculate-{{ qalc_version }}.tar.gz"
    checksum: sha256:a55fbdc14cb183c62a95e430823017b5f958f0758d3476578f8cc05369157c54
  register: tarball

- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - gettext
      - intltool
      - libcurl4-openssl-dev
      - libgmp-dev
      - libicu-dev
      - libmpfr-dev
      - libreadline-dev
      - libxml2-dev

- name: Build libqalculate
  become: true
  shell: |
    set -ex
    rm -rf *
    rm -rf /opt/qalculate
    tar -xf /opt/build/libqalculate-{{ qalc_version }}.tar.gz --strip-components 1
    ./configure --prefix=/opt/qalculate
    make -j{{ ansible_processor_cores }}
    make install
  args:
    executable: /bin/bash
    chdir: /opt/build/libqalculate
  when: tarball.changed

- name: Link qalc
  become: true
  file:
    src: /opt/qalculate/bin/qalc
    dest: /usr/local/bin/qalc
    state: link
