- name: Desktop Linux
  hosts:
   - localhost
  vars:
   home: "{{ lookup('env', 'HOME') }}"
   user: "{{ lookup('env', 'USER') }}"
   git_email: "jennifer@nitori.org"
   gui_packages: true
  connection: local
  roles:
   - common
   - gui
