- hosts:
   - localhost
  vars:
    home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
    git_email: "jennifer.wilcox@adtran.com"
  connection: local
  roles:
    - sway
    - common
    - rust_dev
    - cpp_dev
    - gui
